#!/usr/bin/env python3
"""Declare, and verify, the files a deployment copies out of this repo.

Three repositories serve the same OrgMap application. The renderer has to be
copyable — forking it is the product — so the fix available to a document
(link to it, do not copy it) is not available here. This is the guard instead:
a file naming exactly what must not drift, and a check that says so when it has.

  python3 scripts/shared-manifest.py --write    regenerate SHARED.sha256
  python3 scripts/shared-manifest.py --check    verify it; exit 1 on any drift

The output is plain sha256sum format, so a consumer can verify a copy with
`sha256sum -c SHARED.sha256` and never run this script.

The list below is the single source of truth for what is shared. It is spelled
out rather than globbed on purpose: schemas/example.json, schemas/vdl-current.json
and schemas/cofundeco.json are lab-only datasets that no deployment copies, and a
glob would freeze files the consumers were never given.
"""
import hashlib
import os
import sys

SHARED_FILES = [
    "index.html",
    "vendor/d3.min.js",
    "schemas/vdl-target.json",
    "schemas/vdl-doublelink.json",
    "schemas/barlavento-current.json",
    "schemas/barlavento-vocab.json",
]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "SHARED.sha256")
MANIFEST_NAME = "SHARED.sha256"


def sha256(path):
    """Hash a file in chunks — vendor/d3.min.js is 280 KB and index.html grows."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def parse(text):
    """Read sha256sum format into an ordered list of (hash, path).

    Accepts the two spaces GNU sha256sum writes for text mode and the
    ' *' it writes for binary mode, so a manifest regenerated by hand
    with `sha256sum` still parses.
    """
    entries = []
    for lineno, line in enumerate(text.splitlines(), 1):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        digest, sep, path = line.partition("  ")
        if not sep:
            raise ValueError("%s line %d is not sha256sum format: %r" % (MANIFEST_NAME, lineno, line))
        path = path[1:] if path.startswith("*") else path
        entries.append((digest.strip(), path.strip()))
    return entries


def write():
    missing = [p for p in SHARED_FILES if not os.path.isfile(os.path.join(ROOT, p))]
    if missing:
        for p in missing:
            print("cannot hash %s: file does not exist" % p, file=sys.stderr)
        return 1
    lines = ["%s  %s\n" % (sha256(os.path.join(ROOT, p)), p) for p in SHARED_FILES]
    with open(MANIFEST, "w") as f:
        f.writelines(lines)
    print("wrote %s (%d files)" % (MANIFEST_NAME, len(lines)))
    return 0


def check():
    if not os.path.isfile(MANIFEST):
        print("%s does not exist — run: python3 scripts/shared-manifest.py --write" % MANIFEST_NAME,
              file=sys.stderr)
        return 1

    with open(MANIFEST) as f:
        try:
            entries = parse(f.read())
        except ValueError as e:
            print(str(e), file=sys.stderr)
            return 1

    problems = []

    # The manifest's own file list must match SHARED_FILES, or it is describing
    # a different repo than the one being checked.
    listed = [p for _, p in entries]
    for p in SHARED_FILES:
        if p not in listed:
            problems.append("%s: shared but not listed in %s — regenerate it" % (p, MANIFEST_NAME))
    for p in listed:
        if p not in SHARED_FILES:
            problems.append("%s: listed in %s but no longer shared — regenerate it" % (p, MANIFEST_NAME))

    # Report every mismatch, not just the first: which file drifted is the
    # whole point of the check.
    for digest, path in entries:
        full = os.path.join(ROOT, path)
        if not os.path.isfile(full):
            problems.append("%s: missing (listed in %s)" % (path, MANIFEST_NAME))
            continue
        actual = sha256(full)
        if actual != digest:
            problems.append("%s: differs\n    listed  %s\n    actual  %s" % (path, digest, actual))

    if problems:
        print("%s is out of date — %d problem(s):\n" % (MANIFEST_NAME, len(problems)), file=sys.stderr)
        for p in problems:
            print("  %s" % p, file=sys.stderr)
        print("\nIf the change to these files is intended, regenerate the manifest:",
              file=sys.stderr)
        print("  python3 scripts/shared-manifest.py --write", file=sys.stderr)
        return 1

    print("%s ok (%d files)" % (MANIFEST_NAME, len(entries)))
    return 0


def main(argv):
    if len(argv) != 2 or argv[1] not in ("--write", "--check"):
        print(__doc__.strip().splitlines()[0], file=sys.stderr)
        print("usage: shared-manifest.py [--write|--check]", file=sys.stderr)
        return 2
    return write() if argv[1] == "--write" else check()


if __name__ == "__main__":
    sys.exit(main(sys.argv))
